# Generated by Django 2.0.5 on 2018-05-30 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artykul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('tresc', models.TextField(blank=True, null=True)),
                ('dataUtworzenia', models.DateTimeField(verbose_name='Data utworzenia')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField(blank=True, null=True)),
                ('dataZamieszczenia', models.DateTimeField(verbose_name='Data zamieszczenia')),
                ('artykul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.Artykul')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentarz_odpowiedz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Komentarz')),
                ('odpowiedz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Odpowiedz', to='blog_app.Komentarz')),
            ],
        ),
    ]
