# Generated by Django 2.0.5 on 2018-06-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_komentarz_odpowiedz_datazamieszczenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz_odpowiedz',
            name='komentarz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Komentarz'),
        ),
        migrations.AlterField(
            model_name='komentarz_odpowiedz',
            name='odpowiedz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Odpowiedz', to='blog_app.Komentarz'),
        ),
    ]
