# Generated by Django 2.0.5 on 2018-06-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20180602_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz_odpowiedz',
            name='komentarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Komentarz'),
        ),
    ]
