# Generated by Django 2.0.5 on 2018-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_komentarz_czyodpowiedz'),
    ]

    operations = [
        migrations.AddField(
            model_name='artykul',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to='blog_app/'),
        ),
    ]
