# Generated by Django 2.0.5 on 2018-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_artykul_obraz'),
    ]

    operations = [
        migrations.AddField(
            model_name='artykul',
            name='czyPrywatny',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artykul',
            name='hasło',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
